 version: '2'
 volumes:
  collected_static: {}
 services:
  # ubertool_eco Django front-end
  eco_django:
    build: ./ubertool_eco
    expose:
    - "8080"
    volumes:
    - collected_static:/src/collected_static
    environment:
    - UBERTOOL_REST_SERVER=http://nginx:7777

  # ubertool_ecorest Flask back-end
  ecorest:
    build: ./ubertool_ecorest
    expose:
    - "7777"

  # NGINX web server
  nginx:
    restart: always
    build: ./nginx
    ports:
    - "80:80"
    - "443:443"
    - "7777:7777"
    links:  # Same as depends_on eco_django, but also sets the hostname at which this service can reach the linked service
    - eco_django:uwsgi_django  # Nginx.conf can reference "eco_django" service with the hostname 'uwsgi_django' or 'eco_django'
    - ecorest:uwsgi_flask      # Nginx.conf can reference "ecorest" service with the hostname 'uwsgi_flask' or 'ecorest'
    volumes_from:
    - eco_django:ro  # Mount all volumes from "eco_django" to NGINX, so it can access the collected static files (ro = read-only)
