---
# Ansible Playbook to install Docker on RHEL7
# Uses the OFFICIAL Docker repo (not RHEL Extras repo)

# - include: "os/{{ ansible_os_family }}.yml"

- name: ensure repo is present
  copy:
    src: files/repos/docker-centos7-repo
    dest: /etc/yum.repos.d/docker.repo

- name: ensure docker is installed
  yum:
    name: docker-engine
    state: present


######################################################

- name: ensure config folder is present
  file:
    path: /etc/docker
    state: directory

- name: ensure docker-py module is installed
  pip:
    name: docker-py
    version: 1.9.0
  when: dockerpy

# - name: ensure daemon config file is present
#   template:
#     src: daemon.j2.json
#     dest: /etc/docker/daemon.json
#   notify:
#     - restart docker

- name: ensure unit file folder is present
  file:
    path: /usr/lib/systemd/system
    state: directory

- name: ensure unit file is present & up to date
  copy:
    src: files/docker.service
    dest: /usr/lib/systemd/system/docker.service
  notify:
    - reload unit
    - restart docker

- meta: flush_handlers

- name: ensure starts on system boot
  service:
    name: docker
    enabled: yes
