---
# Ansible Playbook to deploy QED CGI environment
# To run this playbook:
#     ansible-playbook -k -u cgifadmin qed-cgi-environ.yml




- hosts: "{{host}}"  # Executes play on all hosts, this can explicitly name specific hosts if needed
  remote_user: cgifadmin  # User you wish to SSH into remote with
  become: yes  # Become root user
  tasks:
  - redhat_subscription:
    state: present
    username: "{{rhel_username}}"
    password: "{{rhel_passwd}}"
    autosubscribe: true
  - include: "epel-repo-rhel7.yml"  # Install EPEL repo
  - name: update system packages  # yum update -y
    yum:
      name: '*'
      state: latest
  - include: "docker-rhel7.yml"

