---
# Ansible Playbook to deploy QED CGI environment
# To run this playbook:
#     ansible-playbook -k -u cgifadmin qed-cgi-environ.yml


- include: "docker-rhel.yml"

- hosts: cgi3  # Executes play on all hosts, this can explicitly name specific hosts if needed
  remote_user: cgifadmin  # User you wish to SSH into remote with
  become: yes  # Become root user
  tasks:
  - name: update system packages  # yum update -y
    yum: name=update
