---
# Ansible Playbook to deploy QED CGI environment
# To run this playbook:
#     ansible-playbook -k -u cgifadmin qed-cgi-environ.yml


- hosts: "{{host}}"  # Executes play on all hosts, this can explicitly name specific hosts if needed
  remote_user: cgifadmin  # User you wish to SSH into remote with
  become: yes  # Become root user
  vars_files:
    - files/default_vars.yml
  vars_prompt:
    - name: "rhel_username"
      prompt: "Enter RHEL username: "
      private: no
    - name: "rhel_passwd"
      prompt: "Enter RHEL password: "
      private: yes
  tasks:
  - redhat_subscription:
      state: present
      username: "{{rhel_username}}"
      password: "{{rhel_passwd}}"
      autosubscribe: true
  - include: "tasks/epel-repo-rhel7.yml"  # Install EPEL repo
  - name: update system packages  # yum update -y
    yum:
      name: '*'
      state: latest
    async: 900 # Timeout after 15 minutes
    poll: 5    # Check if done every 5 secs
  - include: "tasks/ensure-pip.yml"
  - include: "tasks/docker-rhel7.yml"
