---
# Ansible Playbook to install Docker on RHEL7
# Uses the OFFICIAL Docker repo (not RHEL Extras repo)
# 

- name: ensure repo is present
  copy:
    src: files/docker-centos7-repo
    dest: /etc/yum.repos.d/docker.repo

- name: ensure docker is installed
  yum:
    name: docker-engine
    state: present

######################################################

- name: Ensure Docker config dir exists
  file:
    path: /etc/docker
    state: directory

- name: Ensure `docker-py` module is installed
  pip:
    name: docker-py
    version: 1.9.0

- name: Ensure `docker-data` dir exists
  file:
    path: /var/www/docker-data
    state: directory

- name: Ensure `/etc/systemd/system/docker.service.d` dir exists
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
  # stat: 
  #   path: /var/www/docker-data
  # register: docker_data

# Sets Docker data folder to be "/var/www/docker-data/"
- name: Copy Docker service drop-in file
  copy:
    src: files/docker-data.conf
    dest: /etc/systemd/system/docker.service.d/docker-data.conf
  notify:
    - reload unit
    - restart docker

- meta: flush_handlers

- name: ensure starts on system boot
  service:
    name: docker
    enabled: yes
